name: satcom

topology:
  nodes:
    p1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    p2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    p3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    p4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ar1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ar2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ar3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ar4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    i1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    i2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    cr1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    cr2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    cr3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    cr4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    se1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    se2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    se3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    se4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    pn1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    pn2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    pn3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    pn4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ie1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ie2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ie3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    ie4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    c1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    i3:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    i4:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    server1:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1

    server2:
      kind: cisco_xrd
      image: ios-xr/xrd-control-plane:25.1.1
